"""Ajustar campos do modelo Veiculo

Revision ID: 39e86212581e
Revises: da878dd76122
Create Date: 2025-02-06 10:03:51.086132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e86212581e'
down_revision = 'da878dd76122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ano', sa.Integer(), nullable=True))
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('is_sislog')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sislog', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('ano')
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
