"""Alterando tipo da coluna data_entrega para Date

Revision ID: c5cbc4be2cbb
Revises: fc56af83d554
Create Date: 2025-02-10 09:06:24.721822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cbc4be2cbb'
down_revision = 'fc56af83d554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logistica', schema=None) as batch_op:
        batch_op.alter_column('data_entrega',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logistica', schema=None) as batch_op:
        batch_op.alter_column('data_entrega',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
